old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            
    producers:
        add_skills:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.add_skills', type: direct }

    consumers:
        add_skills:
            connection: default
            exchange_options: { name: 'old_sound_rabbit_mq.add_skills', type: direct }
            queue_options: { name: 'old_sound_rabbit_mq.consumer.add_skills' }
            callback: App\Controller\Amqp\AddSkills\Consumer
            idle_timeout: 300
            idle_timeout_exit_code: 0
            graceful_max_execution:
                timeout: 1800
                exit_code: 0
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
    