version: '3.1'

services:

  php-fpm:
    build: docker
    container_name: 'php'
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    working_dir: /app

  nginx:
    image: nginx
    container_name: 'nginx'
    working_dir: /app
    ports:
      - 7777:80
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf


  php-cli:
    build:
      context: ./
      dockerfile: docker/cli/Dockerfile
    container_name: 'php-cli'
    volumes:
     - ./:/app
    working_dir: /app