<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250209150224 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE lesson (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE marks (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mark INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id BIGINT DEFAULT NULL, task_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS  mark__user_id__ind ON marks (user_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS  mark__task_id__ind ON marks (task_id)');
        $this->addSql('CREATE TABLE skill (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, task_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS  skill__task_id__ind ON skill (task_id)');
        $this->addSql('CREATE TABLE skill_range (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, range INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, task_id BIGINT DEFAULT NULL, skill_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS  skill_range__task_id__ind ON skill_range (task_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS  skill_range__skill_id__ind ON skill_range (skill_id)');
        $this->addSql('CREATE TABLE skill_result (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, result DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id BIGINT DEFAULT NULL, task_id BIGINT DEFAULT NULL, skill_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS  skill_result__user_id__ind ON skill_result (user_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS  skill_result__task_id__ind ON skill_result (task_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS  skill_result__skill_id__ind ON skill_result (skill_id)');
        $this->addSql('CREATE TABLE task (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lesson_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS  task__lesson_id__ind ON task (lesson_id)');
        $this->addSql('CREATE TABLE "user" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, login VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE marks ADD CONSTRAINT fk__mark__user_id FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE marks ADD CONSTRAINT fk__mark__task_id FOREIGN KEY (task_id) REFERENCES task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT fk__mark__task_id FOREIGN KEY (task_id) REFERENCES task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill_range ADD CONSTRAINT fk__skill_range__task_id FOREIGN KEY (task_id) REFERENCES task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill_range ADD CONSTRAINT fk__skill_range__skill_id FOREIGN KEY (skill_id) REFERENCES skill (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill_result ADD CONSTRAINT fk__skill_result__user_id FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill_result ADD CONSTRAINT fk__skill_result__task_id FOREIGN KEY (task_id) REFERENCES task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill_result ADD CONSTRAINT fk__skill_result__skill_id FOREIGN KEY (skill_id) REFERENCES skill (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT fk__task__lesson_id FOREIGN KEY (lesson_id) REFERENCES lesson (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE marks DROP CONSTRAINT fk__mark__user_id');
        $this->addSql('ALTER TABLE marks DROP CONSTRAINT fk__mark__task_id');
        $this->addSql('ALTER TABLE skill DROP CONSTRAINT fk__mark__task_id');
        $this->addSql('ALTER TABLE skill_range DROP CONSTRAINT fk__skill_range__task_id');
        $this->addSql('ALTER TABLE skill_range DROP CONSTRAINT fk__skill_range__skill_id');
        $this->addSql('ALTER TABLE skill_result DROP CONSTRAINT fk__skill_result__user_id');
        $this->addSql('ALTER TABLE skill_result DROP CONSTRAINT fk__skill_result__task_id');
        $this->addSql('ALTER TABLE skill_result DROP CONSTRAINT fk__skill_result__skill_id');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT fk__task__lesson_id');
        $this->addSql('DROP TABLE lesson');
        $this->addSql('DROP TABLE marks');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE skill_range');
        $this->addSql('DROP TABLE skill_result');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE "user"');
    }
}
